Debug = true
DBType = "Postgres"
Address = ":42069"

[PostgresConfig]
  DSN = "host=127.0.0.1 user=pgadmin password=pgadmin_local dbname=lamu-blogapp port=5432 sslmode=disable TimeZone=Asia/Kolkata"

[plugins.p_pwa]
  # If set, /serviceworker.js will serve this file. If empty, p_pwa serves a minimal default.
  serviceWorkerPath = ""

  # If set, /offline will render this view key. If empty, p_pwa serves a minimal offline HTML page.
  offlineViewName = ""

  staticDir = "./pwa_static/"

  PWA_APP_NAME = "Blogapp Lamu"
  PWA_APP_DESCRIPTION = "Blog app made using lamu"
  PWA_APP_THEME_COLOR = "#0A0302"
  PWA_APP_BACKGROUND_COLOR = "#ffffff"
  PWA_APP_DISPLAY = "standalone"
  PWA_APP_SCOPE = "/"
  PWA_APP_ORIENTATION = "any"
  PWA_APP_START_URL = "/"
  PWA_APP_STATUS_BAR_COLOR = "default"
  PWA_APP_DIR = "ltr"
  PWA_APP_LANG = "en-US"

[plugins.p_users]
# Default credentials for admin account, gets created when running `go run main.go generate`
adminEmail = "superadmin@test.com"
adminPassword = "SuperadminPassword1234"
